import { nanoid } from 'nanoid';

export const demoTransactions = [
  // ======== INCOME (Realistic) ========
  {
    id: nanoid(),
    type: 'income',
    title: 'Monthly Salary',
    amount: 45000,
    date: new Date('2025-11-20').toISOString(),
    category: 'Income',
  },
  {
    id: nanoid(),
    type: 'income',
    title: 'Freelance Website Project',
    amount: 18000,
    date: new Date('2025-11-10').toISOString(),
    category: 'Freelance Project',
  },
  {
    id: nanoid(),
    type: 'income',
    title: 'Part-time Work',
    amount: 6000,
    date: new Date('2025-10-28').toISOString(),
    category: 'Part-time Work',
  },
  {
    id: nanoid(),
    type: 'income',
    title: 'Bonus',
    amount: 8000,
    date: new Date('2025-10-15').toISOString(),
    category: 'Income',
  },
  {
    id: nanoid(),
    type: 'income',
    title: 'Freelance Design Task',
    amount: 7000,
    date: new Date('2025-09-29').toISOString(),
    category: 'Freelance Project',
  },

  // ======== EXPENSES (Realistic & nicely distributed) ========
  {
    id: nanoid(),
    type: 'expense',
    title: 'Rent',
    amount: 7000,
    date: new Date('2025-11-05').toISOString(),
    category: 'Rent',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Groceries',
    amount: 3200,
    date: new Date('2025-11-12').toISOString(),
    category: 'Groceries',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Electricity Bill',
    amount: 1800,
    date: new Date('2025-11-09').toISOString(),
    category: 'Electricity Bill',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Fuel / Transport',
    amount: 900,
    date: new Date('2025-11-18').toISOString(),
    category: 'Transport',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Shopping',
    amount: 2500,
    date: new Date('2025-11-03').toISOString(),
    category: 'Shopping',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Internet Bill',
    amount: 800,
    date: new Date('2025-10-25').toISOString(),
    category: 'Internet',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Gym Membership',
    amount: 1500,
    date: new Date('2025-10-22').toISOString(),
    category: 'Gym',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Medicine',
    amount: 650,
    date: new Date('2025-10-18').toISOString(),
    category: 'Medicine',
  },
  {
    id: nanoid(),
    type: 'expense',
    title: 'Food Delivery',
    amount: 550,
    date: new Date('2025-11-01').toISOString(),
    category: 'Food',
  },
];
